--NOMOR 1

select 
sum(
--MENGHITUNG SKENARIO GAJI AKTUAL SETELAH KENAIKAN
	(
	
	--GAJI AWAL
	SALARY
	
	--KENAIKAN GAJI
	+SALARY*CAST(DATEDIFF(YEAR, HIRE_DATE, GETDATE()) AS FLOAT)/100)
	
	--DISETAHUNKAN
	*12
	
	) TOTAL_GAJI_TH_DEPAN_SETELAH_KENAIKAN,

	--BUDGET
	CAST(3450000 as float) BUDGET,


	--APAKAH CUKUP
	CASE 
		WHEN CAST(3450000 as float)>=sum((SALARY+SALARY*CAST(DATEDIFF(YEAR, HIRE_DATE, GETDATE()) AS FLOAT)/100)*12) THEN 'MENCUKUPI'
		ELSE 'TIDAK CUKUP' 
	END AS KESIMPULAN

FROM EMPLOYEES
